# Generated by Django 5.1.1 on 2024-10-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_frequentlyaskedquestions_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('firstname', models.CharField(help_text='Adı', max_length=60, verbose_name='Adı')),
                ('lastname', models.CharField(help_text='Soyadı', max_length=60, verbose_name='Soyadı')),
                ('email', models.EmailField(help_text='E-posta adresi', max_length=254, unique=True, verbose_name='E-posta')),
                ('phone', models.CharField(help_text='Telefon numarası', max_length=20, verbose_name='Telefon numarası')),
                ('service', models.CharField(help_text='Hizmet', max_length=60, verbose_name='Hizmet')),
                ('date', models.DateTimeField(help_text='Tarih', verbose_name='Tarih')),
                ('time', models.DateTimeField(help_text='Saat', verbose_name='Saat')),
                ('content', models.TextField(help_text='Mesaj içeriği', verbose_name='Mesaj')),
            ],
            options={
                'verbose_name': 'İletişim Formu',
                'verbose_name_plural': 'İletişim Formları',
            },
        ),
    ]
