# Generated by Django 5.1.1 on 2024-10-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='time',
            field=models.TimeField(help_text='Saat', verbose_name='Saat'),
        ),
    ]
