# Generated by Django 5.1.1 on 2024-10-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactform_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.CharField(help_text='Tarih', max_length=50, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='time',
            field=models.CharField(help_text='Saat', max_length=50, verbose_name='Saat'),
        ),
    ]
