# Generated by Django 5.1.1 on 2024-10-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contactform_date_alter_contactform_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'verbose_name': 'İletişim Bilgisi', 'verbose_name_plural': 'İletişim Bilgileri'},
        ),
        migrations.AlterModelOptions(
            name='frequentlyaskedquestions',
            options={'verbose_name': 'Sıkça Sorulan Soru', 'verbose_name_plural': 'Sıkça Sorulan Sorular'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Sosyal Medya', 'verbose_name_plural': 'Sosyal Medya'},
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(help_text='E-posta adresi', max_length=254, verbose_name='E-posta'),
        ),
    ]
