# Generated by Django 5.1.1 on 2024-10-12 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(help_text='Kategori Adı', max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('slug', models.CharField(help_text='Kategori filtreleme kısmı (Kategori adı ile aynı ama küçük harflerle olmalıdır)', max_length=100, unique=True, verbose_name='Kategori Slug')),
            ],
            options={
                'verbose_name': 'Hizmet Kategorisi',
                'verbose_name_plural': 'Hizmet Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('title', models.CharField(help_text='Hizmet Adı', max_length=100, unique=True, verbose_name='Hizmet Adı')),
                ('description', models.TextField(help_text='Hizmet Açıklaması', verbose_name='Hizmet Açıklaması')),
                ('category', models.ForeignKey(help_text='Hizmet kategorisi', on_delete=django.db.models.deletion.CASCADE, to='services.category', verbose_name='Hizmet Kategorisi')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(help_text='Paket Adı', max_length=100, unique=True, verbose_name='Paket Adı')),
                ('price', models.FloatField(help_text='Paket Fiyatı', verbose_name='Paket Fiyatı')),
                ('features', models.JSONField(default=list, help_text='Paket Özellikleri', verbose_name='Paket Özellikleri')),
                ('service', models.ForeignKey(help_text='Hizmet', on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Hizmet')),
            ],
            options={
                'verbose_name': 'Hizmet Paketi',
                'verbose_name_plural': 'Hizmet Paketleri',
            },
        ),
    ]
