# Generated by Django 5.1.1 on 2024-10-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.JSONField(help_text='Paket Özellikleri', verbose_name='Paket Özellikleri'),
        ),
    ]
