# Generated by Django 5.1.1 on 2024-10-12 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_package_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='service',
            field=models.ForeignKey(help_text='Hizmet', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.service', verbose_name='Hizmet'),
        ),
    ]
