# Generated by Django 5.1.1 on 2024-10-13 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_package_features_alter_feature_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='features',
        ),
        migrations.AddField(
            model_name='service',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Hizmet paketi', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.package', verbose_name='Hizmet Paketi'),
        ),
        migrations.AlterField(
            model_name='package',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Hizmet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.service', verbose_name='Hizmet'),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.AddField(
            model_name='package',
            name='features',
            field=models.JSONField(blank=True, help_text='Paket Özellikleri', null=True, verbose_name='Paket Özellikleri'),
        ),
    ]
