# Generated by Django 5.1.1 on 2024-10-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_package_features_service_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='package',
        ),
        migrations.AddField(
            model_name='service',
            name='package',
            field=models.ManyToManyField(blank=True, help_text='Hizmet Paketi / Paketleri', null=True, related_name='services', to='services.package', verbose_name='Hizmet Paketleri'),
        ),
    ]
