# Generated by Django 5.1.1 on 2024-10-13 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_service_package_service_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='package',
        ),
        migrations.AddField(
            model_name='service',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Hizmet paketi', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.package', verbose_name='Hizmet Paketi'),
        ),
    ]
