# Generated by Django 5.1.1 on 2024-10-13 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_service_package_service_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
    ]
