# Generated by Django 5.1.1 on 2024-10-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_package_name_remove_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(blank=True, help_text='Paket Adı', max_length=100, null=True, unique=True, verbose_name='Paket Adı'),
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.FloatField(blank=True, help_text='Paket Fiyatı', null=True, verbose_name='Paket Fiyatı'),
        ),
    ]
