# Generated by Django 5.1.1 on 2024-10-13 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_package_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='features',
        ),
        migrations.RemoveField(
            model_name='service',
            name='package',
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.CharField(blank=True, help_text='Paket Fiyatı', max_length=50, null=True, verbose_name='Paket Fiyatı'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(help_text='Hizmet kategorisi', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category', verbose_name='Hizmet Kategorisi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Hizmet Açıklaması', verbose_name='Hizmet Açıklaması'),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('description', models.CharField(max_length=255, verbose_name='Özellik Açıklaması')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.package', verbose_name='Paket')),
            ],
            options={
                'verbose_name': 'Paket Özelliği',
                'verbose_name_plural': 'Paket Özellikleri',
            },
        ),
    ]
