# Generated by Django 5.1.1 on 2024-10-13 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_package_features_remove_service_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.CharField(help_text='Özellik açıklaması, madde madde ekleneceği için tek satırlık eklemeler önerilir.', max_length=255, verbose_name='Özellik Açıklaması'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='package',
            field=models.ForeignKey(help_text='Özellik eklemek istediğiniz paketi seçin.', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.package', verbose_name='Paket'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.FloatField(blank=True, help_text='Paket Fiyatı', max_length=50, null=True, verbose_name='Paket Fiyatı'),
        ),
        migrations.AlterField(
            model_name='package',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Paket eklemek istediğiniz hizmeti seçin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.service', verbose_name='Hizmet'),
        ),
    ]
