# Generated by Django 5.1.1 on 2024-10-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_feature_description_alter_feature_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Paket Fiyatı', max_digits=10, null=True, verbose_name='Paket Fiyatı'),
        ),
    ]
