# Generated by Django 5.1.1 on 2024-10-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.CharField(blank=True, help_text='Paket Fiyatı', max_length=20, null=True, verbose_name='Paket Fiyatı'),
        ),
    ]
