# Generated by Django 5.1.1 on 2024-10-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True, help_text='Hizmet aktif mi?', verbose_name='Aktif'),
        ),
    ]
