# Generated by Django 5.1.1 on 2024-10-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_service_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='active',
            field=models.BooleanField(choices=[('active', 'Aktif'), ('inactive', 'Pasif')], default='active', help_text='Hizmet aktif mi?', verbose_name='Aktif'),
        ),
    ]
