# Generated by Django 5.1.1 on 2024-10-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_service_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True, help_text='Hizmet aktif mi?', verbose_name='Aktif'),
        ),
    ]
