# Generated by Django 5.1.1 on 2024-10-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_service_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseOurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('title', models.CharField(help_text='Hizmet adı', max_length=100, unique=True, verbose_name='Hizmet Adı')),
                ('description', models.TextField(help_text='Hizmet açıklaması', verbose_name='Hizmet Açıklaması')),
            ],
            options={
                'verbose_name': 'Neden Hizmetlerimizi Seçmelisiniz İçeriği',
                'verbose_name_plural': 'Neden Hizmetlerimizi Seçmelisiniz İçerikleri',
            },
        ),
    ]
