# Generated by Django 5.1.1 on 2024-10-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_whychooseourservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(help_text='Hizmet Içerik Adı', max_length=100, unique=True, verbose_name='Hizmet Içerik Adı')),
                ('description', models.TextField(help_text='Hizmet Içerik Açıklaması', verbose_name='Hizmet Içerik Açıklaması')),
            ],
            options={
                'verbose_name': 'Hizmetler İçerik Yazısı',
                'verbose_name_plural': 'Hizmetler İçerik Yazıları',
            },
        ),
    ]
