# Generated by Django 5.1.1 on 2024-10-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_footer_header_delete_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('company_name', models.CharField(help_text='Firma adı', max_length=100, unique=True, verbose_name='Firma Adı')),
                ('logo', models.ImageField(blank=True, help_text='Header logosu (firma logosu)', null=True, upload_to='header', verbose_name='Logo')),
                ('description', models.TextField(blank=True, help_text='Firma açıklaması, zorunlu değil footer için kullanılacak', null=True, verbose_name='Firma Açıklaması')),
            ],
            options={
                'verbose_name': 'Genel İçerik (Header / Navbar / Vs.)',
                'verbose_name_plural': 'Genel İçerikler',
            },
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='Header',
        ),
    ]
