# Generated by Django 5.1.1 on 2024-10-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_general_delete_footer_delete_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('title', models.CharField(help_text='Teklif baslığı', max_length=100, unique=True, verbose_name='Teklif Baslığı')),
                ('description', models.TextField(blank=True, help_text='Teklif açıklaması', null=True, verbose_name='Teklif Açıklaması')),
            ],
            options={
                'verbose_name': 'Teklif (Offer) İçeriği',
                'verbose_name_plural': 'Teklif (Offer) İçerikleri',
            },
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'verbose_name': 'Genel İçerik (Header / Footer / Adres)', 'verbose_name_plural': 'Genel İçerikler'},
        ),
    ]
