# Generated by Django 5.1.1 on 2024-10-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_offer_alter_general_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('title', models.CharField(help_text='Seo (site) başlığı', max_length=100, unique=True, verbose_name='Seo (Site) Başlığı')),
                ('description', models.TextField(help_text='Seo (site) açıklaması', verbose_name='Seo (Site) Açıklaması')),
                ('keywords', models.TextField(help_text='Seo (site) anahtar kelimeler, (a,b,c) şeklinde yazılmalıdır.', verbose_name='Seo (Site) Anahtar Kelimeler')),
                ('author', models.CharField(help_text='Seo (site) yazarı', max_length=100, verbose_name='Seo (Site) Yazarı')),
                ('ogTitle', models.CharField(help_text="Seo (site) Og'nin başlığı", max_length=100, verbose_name="Seo (Site) Og'nin Başlığı")),
                ('ogDescription', models.TextField(help_text="Seo (site) Og'nin açıklaması", verbose_name="Seo (Site) Og'nin Açıklaması")),
                ('ogUrl', models.URLField(help_text="Seo (site) Og'nin url", max_length=100, verbose_name="Seo (Site) Og'nin Url")),
                ('ogImage', models.ImageField(help_text="Seo (site) Og'nin resmi", upload_to='seo', verbose_name="Seo (Site) Og'nin Resmi")),
                ('twitterTitle', models.CharField(help_text='Seo (site) Twitter başlığı', max_length=100, verbose_name='Seo (Site) Twitter Başlığı')),
                ('twitterDescription', models.TextField(help_text='Seo (site) Twitter açıklaması', verbose_name='Seo (Site) Twitter Açıklaması')),
                ('twitterImage', models.ImageField(help_text='Seo (site) Twitter resmi', upload_to='seo', verbose_name='Seo (Site) Twitter Resmi')),
                ('favicon', models.ImageField(help_text='Seo (site) favicon resmi (.ico uzantılı dosyalar önerilir.)', upload_to='seo', verbose_name='Seo (Site) Favicon')),
            ],
            options={
                'verbose_name': 'Seo (Site) Ayarı',
                'verbose_name_plural': 'Seo (Site) Ayarları',
            },
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'verbose_name': 'Genel İçerik ( Header / Footer )', 'verbose_name_plural': 'Genel İçerikler'},
        ),
    ]
