# Generated by Django 5.1.1 on 2024-10-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('title', models.CharField(help_text='Hero section başlığı', max_length=100, verbose_name='Hero Section Başlığı')),
                ('description', models.TextField(help_text='Her section açıklaması', verbose_name='Hero Section Açıklama')),
                ('image', models.ImageField(help_text='Hero section fotoğrafı', upload_to='home', verbose_name='Hero Section Fotoğrafı')),
            ],
            options={
                'verbose_name': 'Home Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
    ]
