# Generated by Django 5.1.1 on 2024-10-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_herosection_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('title', models.CharField(help_text='CTA section başlığı', max_length=150, verbose_name='CTA Section Başlığı')),
                ('description', models.TextField(help_text='CTA section açıklaması', verbose_name='CTA Section Açıklama')),
            ],
            options={
                'verbose_name': 'Ana Sayfa CTA Section',
                'verbose_name_plural': 'Ana Sayfa CTA Sectionları',
            },
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Ana Sayfa Hero Section', 'verbose_name_plural': 'Ana Sayfa Hero Sectionları'},
        ),
    ]
