# Generated by Django 5.1.1 on 2024-10-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ctasection_alter_herosection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctasection',
            options={'verbose_name': 'Ana Sayfa CTA Bölümü', 'verbose_name_plural': 'Ana Sayfa CTA Bölümleri'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Ana Sayfa Hero Bölümü', 'verbose_name_plural': 'Ana Sayfa Hero Bölümüleri'},
        ),
    ]
