# Generated by Django 5.1.1 on 2024-10-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourapproach',
            options={'verbose_name': 'Yaklaşımımız İçeriği', 'verbose_name_plural': 'Yaklaşımımız İçerikleri'},
        ),
    ]
