# Generated by Django 5.1.1 on 2024-10-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_ourapproach_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscard',
            options={'verbose_name': 'Kartvizit İçeriği', 'verbose_name_plural': 'Kartvizit İçerikleri'},
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='subtitle',
            field=models.CharField(help_text='Kartvizit alt başlığı', max_length=50, verbose_name='Alt Başlık'),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='title',
            field=models.CharField(help_text='Kartvizit başlığı', max_length=50, verbose_name='Başlık'),
        ),
    ]
