# Generated by Django 5.1.1 on 2024-10-12 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(help_text='Kategori Adı', max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(help_text='Kategori filtreleme kısmı (Kategori adı ile aynı ama küçük harflerle olmalıdır)', max_length=100, unique=True, verbose_name='Kategori Slug')),
            ],
            options={
                'verbose_name': 'Portfolyo Kategorisi',
                'verbose_name_plural': 'Portfolyo Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('image', models.ImageField(blank=True, help_text='Fotoğraf', null=True, upload_to='portfolio', verbose_name='Fotoğraf')),
                ('name', models.CharField(help_text='Fotoğraf Adı / Proje Adı', max_length=100, verbose_name='Fotoğraf Adı')),
                ('category', models.ForeignKey(help_text='Portfolyo kategorisi', on_delete=django.db.models.deletion.CASCADE, to='portfolio.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Portfolyo Fotoğrafı',
                'verbose_name_plural': 'Portfolyo Fotoğrafları',
            },
        ),
    ]
