# Generated by Django 5.1.1 on 2024-10-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(help_text='Kategori filtreleme kısmı (Kategori adı ile aynı ama küçük harflerle olmalıdır)', max_length=100, unique=True, verbose_name='Kategori Slug'),
        ),
    ]
