# Generated by Django 5.1.1 on 2024-10-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Work',
        ),
    ]
