# Generated by Django 5.1.1 on 2024-10-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(help_text='Firma adı', max_length=50, verbose_name='Firma Adı')),
                ('logo', models.ImageField(blank=True, help_text='Firma logosu', null=True, upload_to='references', verbose_name='Firma Logosu')),
            ],
            options={
                'verbose_name': 'Firma Portfolyosu',
                'verbose_name_plural': 'Firmalar',
            },
        ),
    ]
