# Generated by Django 5.1.1 on 2024-10-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTestimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(help_text='Müşteri adı', max_length=100, verbose_name='Müşteri Adı')),
                ('company', models.CharField(help_text='Firma adı', max_length=100, verbose_name='Firma Adı')),
                ('image', models.ImageField(blank=True, help_text='Müşteri fotoğrafı', null=True, upload_to='references', verbose_name='Müşteri Fotoğrafı')),
                ('quote', models.TextField(help_text='Müşteri görüşü', verbose_name='Müşteri Görüşü')),
            ],
            options={
                'verbose_name': 'Müşteri Görüşü',
                'verbose_name_plural': 'Müşteri Görüşleri',
            },
        ),
        migrations.AlterModelOptions(
            name='customerportfolio',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firma Portfolyosu'},
        ),
    ]
