# Generated by Django 5.1.1 on 2024-10-11 23:50

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_customertestimonials_alter_customerportfolio_options'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('title', models.CharField(help_text='Proje adı', max_length=150, verbose_name='Proje Adı')),
                ('description', models.TextField(help_text='Açıklama', verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, help_text='Proje fotoğrafı', null=True, upload_to='featured_projects', verbose_name='Proje Fotoğrafı')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Öne Çıkan Proje',
                'verbose_name_plural': 'Öne Çıkan Projeler',
            },
        ),
    ]
