# Generated by Django 5.1.1 on 2024-10-12 00:03

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_featuredprojects'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Etiket Adı')),
            ],
            options={
                'verbose_name': 'Etiket',
                'verbose_name_plural': 'Etiketler',
            },
        ),
        migrations.AlterField(
            model_name='featuredprojects',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Virgülle ayrılmış etiketler(Tag1, Tag2, Tag3) gibi', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
