# Generated by Django 5.1.1 on 2024-10-12 00:30

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_tag_alter_featuredprojects_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectoralRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('title', models.CharField(help_text='Etkinlik adı', max_length=150, verbose_name='Etkinlik')),
                ('description', models.CharField(help_text='Açıklama', max_length=500, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Etkinlik',
                'verbose_name_plural': 'Etkinlikler',
            },
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='featuredprojects',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Virgülle ayrılmış etiketler(Tag1, Tag2, Tag3) gibi', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiketler'),
        ),
    ]
