# Generated by Django 5.1.1 on 2024-10-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_sectoralrecognition_delete_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectoralrecognition',
            name='description',
            field=models.CharField(help_text='Etkinlik açıklaması', max_length=500, verbose_name='Açıklama'),
        ),
    ]
